import type { WorkflowDefinition } from "./types";

/**
 * General Customers program (non-VIP) — portal, sales, fulfillment,
 * SXM/SYB product journeys, and support. Internal companions included
 * where they belong to the same business process.
 */

export const CUSTOMER_WORKFLOWS: WorkflowDefinition[] = [
  {
    id: "portal-customer-welcome",
    sequenceKey: "Portal.Core.Welcome",
    name: "Customer Portal Welcome",
    businessProcess: "New customer portal welcome",
    departmentSlug: "customers",
    processType: "trigger",
    summary: "Welcome a new customer to the portal with login credentials (PortWelcome).",
    sourceJobs: ["CRM", "CustomerCommunications", "OnlineSign"],
    enrollment: {
      summary: "New customer portal account created.",
      details: [],
    },
    start: {
      summary: "Portal account created.",
      triggers: ["Event: PortWelcome"],
    },
    stop: {
      summary: "After welcome email sends.",
      details: [],
    },
    suppression: { summary: "Transactional portal mail.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "New portal account",
        triggerKind: "event",
        triggerDetail: "PortWelcome",
        note: "CRM · CustomerCommunications · OnlineSign",
        next: "port-welcome",
      },
      {
        id: "port-welcome",
        kind: "email",
        label: "Portal welcome",
        emailKey: "PortWelcome",
        subject: "Welcome! Access Your Dynamic Media Customer Portal",
        next: "exit",
      },
      { id: "exit", kind: "exit", label: "Welcome sent", exitTone: "success" },
    ],
    emails: [
      {
        key: "PortWelcome",
        name: "Welcome to Dynamic Media!",
        subject: "Welcome! Access Your Dynamic Media Customer Portal",
        purpose: "Portal welcome to new customer",
        trigger: "event",
        apps: ["CRM", "CustomerCommunications", "OnlineSign"],
        step: 1,
      },
    ],
  },

  {
    id: "dealer-signup",
    sequenceKey: "Sales.DealerSignup",
    name: "Dealer Signup",
    businessProcess: "Customer signs up via dealer → online sign → portal welcome",
    departmentSlug: "customers",
    processType: "trigger",
    summary:
      "Customer-facing path when a dealer originates the deal: optional online signup link on behalf of the dealer (SndDlrOnSgn) → Customer Portal welcome (PrtDlrWlc).",
    sourceJobs: ["CRM", "CustomerCommunications", "CustomerPortal", "OnlineSign"],
    enrollment: {
      summary: "Customer is signing up through a dealer partner.",
      details: [
        "Emails are sent to the customer on behalf of the dealer.",
        "Dealer partner onboarding (invite / Dealer Portal welcome) is a separate Technician & Dealer workflow.",
      ],
    },
    start: {
      summary: "Dealer-sourced customer signup begins.",
      triggers: ["Manual: SndDlrOnSgn", "Event: PrtDlrWlc"],
    },
    stop: {
      summary: "After portal welcome (and sign link if sent).",
      details: [],
    },
    suppression: {
      summary: "Do not also send PortWelcome for the same portal standup.",
      details: [],
    },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Dealer-sourced customer",
        triggerKind: "event",
        triggerDetail: "Customer signup via dealer",
        note: "CRM · dealer sales",
        next: "sign-gate",
      },
      {
        id: "sign-gate",
        kind: "branch",
        label: "Online signup link?",
        branches: [
          {
            id: "yes",
            label: "Send on behalf of dealer",
            condition: "Agent sends SndDlrOnSgn",
            next: "onsign",
            tone: "success",
          },
          {
            id: "no",
            label: "Skip",
            condition: "Already signed / no link needed",
            next: "welcome",
            tone: "neutral",
          },
        ],
      },
      {
        id: "onsign",
        kind: "email",
        label: "Signup link (via dealer)",
        emailKey: "SndDlrOnSgn",
        subject: "@Customer.Name@, Dynamic Media Online Sign Link",
        note: "On behalf of dealer",
        next: "welcome",
      },
      {
        id: "welcome",
        kind: "email",
        label: "Customer portal welcome",
        emailKey: "PrtDlrWlc",
        subject: "Welcome to Dynamic Media!",
        note: "Customer Portal credentials",
        next: "exit",
      },
      {
        id: "exit",
        kind: "exit",
        label: "Dealer signup complete",
        exitTone: "success",
      },
    ],
    emails: [
      {
        key: "SndDlrOnSgn",
        name: "Dealer online sign link",
        subject: "@Customer.Name@, Dynamic Media Online Sign Link",
        purpose: "Customer signup / online agreement on behalf of the dealer",
        trigger: "manual",
        apps: ["CustomerPortal", "CRM"],
        step: 1,
      },
      {
        key: "PrtDlrWlc",
        name: "Dealer-sourced portal welcome",
        subject: "Welcome to Dynamic Media!",
        purpose: "Customer Portal welcome after dealer-originated signup",
        trigger: "event",
        apps: ["CRM", "CustomerCommunications"],
        step: 2,
      },
    ],
  },

  {
    id: "portal-customer-password",
    sequenceKey: "Portal.Core.PasswordReset",
    name: "Customer Portal Password Reset",
    businessProcess: "Customer portal password reset",
    departmentSlug: "customers",
    processType: "trigger",
    summary: "On-demand customer portal password reset (PortPassRes).",
    sourceJobs: ["CRM", "CustomerCommunications", "CustomerPortal", "DM_Store"],
    enrollment: {
      summary: "Customer requests or is issued a portal password reset.",
      details: [],
    },
    start: {
      summary: "Password reset requested.",
      triggers: ["Event: PortPassRes"],
    },
    stop: {
      summary: "After reset email sends.",
      details: [],
    },
    suppression: { summary: "Transactional portal mail.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Password reset requested",
        triggerKind: "event",
        triggerDetail: "PortPassRes",
        next: "port-reset",
      },
      {
        id: "port-reset",
        kind: "email",
        label: "Password reset",
        emailKey: "PortPassRes",
        subject: "Your Dynamic Media Password Has Been Reset",
        next: "exit",
      },
      { id: "exit", kind: "exit", label: "Reset sent", exitTone: "success" },
    ],
    emails: [
      {
        key: "PortPassRes",
        name: "Dynamic Media Customer Portal - Password Reset",
        subject: "Your Dynamic Media Password Has Been Reset",
        purpose: "Portal password reset",
        trigger: "event",
        apps: ["CRM", "CustomerCommunications", "CustomerPortal", "DM_Store"],
      },
    ],
  },

  {
    id: "sales-proposal-close",
    sequenceKey: "Sales.Close",
    name: "Proposal & Close",
    businessProcess: "Sales proposal → online sign → optional rebate",
    departmentSlug: "customers",
    processType: "manual",
    summary:
      "Manual sales path: send proposal (SndPrpsl) → online sign link (SndOnSgn) → optional rebate (SENDREBATE).",
    sourceJobs: ["CRM", "CustomerPortal"],
    enrollment: {
      summary: "Sales agent initiates proposal on a deal.",
      details: ["Agent decides timing — not a day ladder."],
    },
    start: {
      summary: "Agent sends proposal.",
      triggers: ["Manual: SndPrpsl", "Manual: SndOnSgn", "Manual: SENDREBATE"],
    },
    stop: {
      summary: "Deal signed, lost, or rebate sent.",
      details: [],
    },
    suppression: { summary: "Agent-controlled; avoid duplicate same-day sends.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Sales agent action",
        triggerKind: "manual",
        triggerDetail: "CRM send proposal / sign / rebate",
        next: "proposal",
      },
      {
        id: "proposal",
        kind: "email",
        label: "Send proposal",
        emailKey: "SndPrpsl",
        subject: "Your Music Proposal from Dynamic Media",
        next: "sign",
      },
      {
        id: "sign",
        kind: "email",
        label: "Online sign link",
        emailKey: "SndOnSgn",
        subject: "Your Dynamic Media Online Agreement",
        next: "rebate-gate",
      },
      {
        id: "rebate-gate",
        kind: "branch",
        label: "Send rebate?",
        branches: [
          {
            id: "yes",
            label: "Yes",
            condition: "Eligible — agent sends rebate",
            next: "rebate",
            tone: "neutral",
          },
          {
            id: "no",
            label: "No",
            condition: "Skip rebate",
            next: "exit",
            tone: "neutral",
          },
        ],
      },
      {
        id: "rebate",
        kind: "email",
        label: "Rebate offer",
        emailKey: "SENDREBATE",
        subject: "Your Rebate Information",
        next: "exit",
      },
      { id: "exit", kind: "exit", label: "Sales path complete", exitTone: "success" },
    ],
    emails: [
      {
        key: "SndPrpsl",
        name: "Send proposal to customer",
        subject: "Your Music Proposal from Dynamic Media",
        purpose: "Email proposal",
        trigger: "manual",
        apps: ["CRM"],
        step: 1,
      },
      {
        key: "SndOnSgn",
        name: "Send online sign link",
        subject: "Your Dynamic Media Online Agreement",
        purpose: "Online agreement link",
        trigger: "manual",
        apps: ["CRM", "CustomerPortal"],
        step: 2,
      },
      {
        key: "SENDREBATE",
        name: "Rebate offer",
        subject: "Your Rebate Information",
        purpose: "Manual rebate offer",
        trigger: "manual",
        apps: ["CRM"],
      },
    ],
  },

  {
    id: "fulfillment-core-order",
    sequenceKey: "Fulfillment.Core",
    name: "Order → Ship → Warranty",
    businessProcess: "General customer order fulfillment",
    departmentSlug: "customers",
    processType: "trigger",
    summary:
      "DM Store order confirmation (DMSTCONFRM / DMSTCMSYB) → shipping (OrderShip) → optional warranty (SENDWRNTY).",
    sourceJobs: ["DM_Store", "CRM", "ShipStationSync"],
    enrollment: {
      summary: "Customer places a Dynamic Media store order.",
      details: ["Template variant: standard vs SYB store confirm."],
    },
    start: {
      summary: "Order confirmed in DM Store.",
      triggers: ["Event: DMSTCONFRM / DMSTCMSYB", "Event: OrderShip", "Event: SENDWRNTY"],
    },
    stop: {
      summary: "After ship (and warranty if applicable).",
      details: [],
    },
    suppression: { summary: "One confirm variant per order.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Order confirmed",
        triggerKind: "event",
        triggerDetail: "DM Store order",
        next: "confirm-variant",
      },
      {
        id: "confirm-variant",
        kind: "branch",
        label: "Confirm template?",
        branches: [
          {
            id: "std",
            label: "Standard",
            condition: "DMSTCONFRM",
            next: "confirm",
            tone: "neutral",
          },
          {
            id: "syb",
            label: "SYB store",
            condition: "DMSTCMSYB",
            next: "confirm-syb",
            tone: "neutral",
          },
        ],
      },
      {
        id: "confirm",
        kind: "email",
        label: "Order confirmation",
        emailKey: "DMSTCONFRM",
        subject: "Your Dynamic Media Order Is Confirmed",
        next: "ship",
      },
      {
        id: "confirm-syb",
        kind: "email",
        label: "Order confirmation (SYB)",
        emailKey: "DMSTCMSYB",
        subject: "Your Dynamic Media Order Is Confirmed",
        next: "ship",
      },
      {
        id: "ship",
        kind: "email",
        label: "Shipping confirmation",
        emailKey: "OrderShip",
        subject: "Your Order Is on Its Way",
        next: "warranty-gate",
      },
      {
        id: "warranty-gate",
        kind: "branch",
        label: "Send warranty?",
        branches: [
          {
            id: "yes",
            label: "Yes",
            condition: "Warranty / RMA path",
            next: "warranty",
            tone: "neutral",
          },
          {
            id: "no",
            label: "No",
            condition: "Skip",
            next: "exit",
            tone: "neutral",
          },
        ],
      },
      {
        id: "warranty",
        kind: "email",
        label: "Warranty form",
        emailKey: "SENDWRNTY",
        subject: "Your Warranty Information",
        next: "exit",
      },
      { id: "exit", kind: "exit", label: "Fulfillment complete", exitTone: "success" },
    ],
    emails: [
      {
        key: "DMSTCONFRM",
        name: "Music for Business - Order Confirmation",
        subject: "Your Dynamic Media Order Is Confirmed",
        purpose: "Order confirmation",
        trigger: "event",
        apps: ["DM_Store"],
        step: 1,
      },
      {
        key: "DMSTCMSYB",
        name: "Music for Business - Order Confirmation (SYB)",
        subject: "Your Dynamic Media Order Is Confirmed",
        purpose: "Order confirmation SYB variant",
        trigger: "event",
        apps: ["DM_Store"],
        step: 1,
      },
      {
        key: "OrderShip",
        name: "Dynamic Media Shipping Confirmation",
        subject: "Your Order Is on Its Way",
        purpose: "Shipping confirmation",
        trigger: "event",
        apps: ["CRM", "ShipStationSync"],
        step: 2,
      },
      {
        key: "SENDWRNTY",
        name: "Warranty form and instructions",
        subject: "Your Warranty Information",
        purpose: "Warranty form link",
        trigger: "event",
        apps: ["CRM"],
      },
    ],
  },

  {
    id: "sxm-free-trial",
    sequenceKey: "Sales.SXM.Trial",
    name: "SiriusXM Free Trial",
    businessProcess: "SXM free trial approve / decline / resend",
    departmentSlug: "customers",
    processType: "trigger",
    summary:
      "Customer trial active (ACTDEMO), declined (REJECTDEMO), or resend (REACTDEMO). Internal NOTIFYDEMO when a trial account is created.",
    sourceJobs: ["CRM"],
    enrollment: {
      summary: "Lead requests SiriusXM business free trial.",
      details: ["Internal companion on create."],
    },
    start: {
      summary: "SXM free trial decision event.",
      triggers: ["Event: ACTDEMO / REJECTDEMO / REACTDEMO", "Internal: NOTIFYDEMO"],
    },
    stop: {
      summary: "After customer outcome email (+ internal notify if created).",
      details: [],
    },
    suppression: { summary: "Mutually exclusive approve vs decline.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "SXM trial request",
        triggerKind: "event",
        triggerDetail: "Free trial decision",
        next: "outcome",
      },
      {
        id: "outcome",
        kind: "branch",
        label: "Trial outcome?",
        branches: [
          {
            id: "ok",
            label: "Approved",
            condition: "Trial activated",
            next: "active",
            tone: "success",
          },
          {
            id: "no",
            label: "Declined",
            condition: "Not approved",
            next: "declined",
            tone: "danger",
          },
          {
            id: "resend",
            label: "Resend",
            condition: "Resend credentials",
            next: "resend",
            tone: "neutral",
          },
        ],
      },
      {
        id: "active",
        kind: "email",
        label: "Trial active",
        emailKey: "ACTDEMO",
        subject: "Your SiriusXM Business Free Trial Is Active!",
        next: "internal",
      },
      {
        id: "declined",
        kind: "email",
        label: "Trial declined",
        emailKey: "REJECTDEMO",
        subject: "We Couldn't Process Your Free Trial Request",
        next: "exit",
      },
      {
        id: "resend",
        kind: "email",
        label: "Resend trial",
        emailKey: "REACTDEMO",
        subject: "Your SiriusXM Business Free Trial Is Ready",
        next: "exit",
      },
      {
        id: "internal",
        kind: "email",
        label: "Internal: trial created",
        emailKey: "NOTIFYDEMO",
        subject: "Free trial account created",
        note: "Internal staff companion",
        next: "exit",
      },
      { id: "exit", kind: "exit", label: "Trial path complete", exitTone: "success" },
    ],
    emails: [
      {
        key: "ACTDEMO",
        name: "Welcome to your SiriusXM Business free trial!",
        subject: "Your SiriusXM Business Free Trial Is Active!",
        purpose: "SXM free trial active",
        trigger: "event",
        apps: ["CRM"],
        step: 1,
      },
      {
        key: "REJECTDEMO",
        name: "SiriusXM free trial declined",
        subject: "We Couldn't Process Your Free Trial Request",
        purpose: "SXM trial declined",
        trigger: "event",
        apps: ["CRM"],
      },
      {
        key: "REACTDEMO",
        name: "SiriusXM free trial resend",
        subject: "Your SiriusXM Business Free Trial Is Ready",
        purpose: "Resend trial credentials",
        trigger: "event",
        apps: ["CRM"],
      },
      {
        key: "NOTIFYDEMO",
        name: "SXM trial created (ops)",
        subject: "Free trial account created",
        purpose: "Internal — trial account created for lead",
        trigger: "event",
        apps: ["CRM"],
      },
    ],
  },

  {
    id: "sxm-service-activation",
    sequenceKey: "Service.SXM.Activation",
    name: "SiriusXM Service Activation",
    businessProcess: "SXM streaming / satellite activation",
    departmentSlug: "customers",
    processType: "trigger",
    summary:
      "Customer activation credentials for streaming (SENDCRED) or satellite (SATSENDCRED). Internal SXMSVCERROR on failure.",
    sourceJobs: [
      "ActivateOnDelivery",
      "CRM",
      "CustomerPortal",
      "SMS.DM_CRM.ServiceStatusProcessor",
    ],
    enrollment: {
      summary: "SXM service activates or fails to activate.",
      details: [],
    },
    start: {
      summary: "SXM activation event.",
      triggers: ["Event: SENDCRED / SATSENDCRED", "Event: SXMSVCERROR"],
    },
    stop: {
      summary: "After success or error notify.",
      details: [],
    },
    suppression: { summary: "Streaming vs satellite mutually exclusive per radio.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "SXM activation",
        triggerKind: "event",
        triggerDetail: "Activate on delivery / status",
        next: "result",
      },
      {
        id: "result",
        kind: "branch",
        label: "Result?",
        branches: [
          {
            id: "stream",
            label: "Streaming OK",
            condition: "SENDCRED",
            next: "cred",
            tone: "success",
          },
          {
            id: "sat",
            label: "Satellite OK",
            condition: "SATSENDCRED",
            next: "sat",
            tone: "success",
          },
          {
            id: "err",
            label: "Error",
            condition: "Activation failed",
            next: "error",
            tone: "danger",
          },
        ],
      },
      {
        id: "cred",
        kind: "email",
        label: "Streaming credentials",
        emailKey: "SENDCRED",
        subject: "Your SiriusXM Streaming Service Is Now Active",
        next: "exit-ok",
      },
      {
        id: "sat",
        kind: "email",
        label: "Satellite ready",
        emailKey: "SATSENDCRED",
        subject: "Your SiriusXM Satellite Service Is Ready",
        next: "exit-ok",
      },
      {
        id: "error",
        kind: "email",
        label: "Internal: activation error",
        emailKey: "SXMSVCERROR",
        subject: "SXM activation / termination error",
        note: "Internal staff",
        next: "exit-err",
      },
      { id: "exit-ok", kind: "exit", label: "Customer activated", exitTone: "success" },
      { id: "exit-err", kind: "exit", label: "Ops resolving error", exitTone: "danger" },
    ],
    emails: [
      {
        key: "SENDCRED",
        name: "SiriusXM streaming activation",
        subject: "Your SiriusXM Streaming Service Is Now Active",
        purpose: "Streaming credentials + welcome",
        trigger: "event",
        apps: ["ActivateOnDelivery", "CRM", "CustomerPortal"],
        step: 1,
      },
      {
        key: "SATSENDCRED",
        name: "SiriusXM satellite activation",
        subject: "Your SiriusXM Satellite Service Is Ready",
        purpose: "Satellite activation",
        trigger: "event",
        apps: [
          "ActivateOnDelivery",
          "SMS.DM_CRM.ServiceStatusProcessor",
          "CustomerPortal",
        ],
        step: 1,
      },
      {
        key: "SXMSVCERROR",
        name: "SXM activation error",
        subject: "SXM activation / termination error",
        purpose: "Internal — failure to activate/terminate radio",
        trigger: "event",
        apps: ["ActivateOnDelivery"],
      },
    ],
  },

  {
    id: "syb-trial-to-paid",
    sequenceKey: "Sales.SYB",
    name: "Soundtrack Trial → Paid",
    businessProcess: "SYB trial, activation, conversion tasks",
    departmentSlug: "customers",
    processType: "trigger",
    summary:
      "Customer trial active/declined and activation confirm, with internal task/conversion/error companions (SYBNOTIFY, SYBNOTDEMO, SYBCTNOTIFY, SYBFT2PAID, SYBSVCERROR).",
    sourceJobs: [
      "CRM",
      "CustomerCommunications",
      "ActivateOnDelivery",
      "DM_Store",
      "PaymentStatusSync",
      "SMS.DM_CRM.ServiceStatusProcessor",
    ],
    enrollment: {
      summary: "Soundtrack (SYB) trial or paid activation path.",
      details: ["Customer + internal task emails in one program."],
    },
    start: {
      summary: "SYB trial or activation event.",
      triggers: [
        "Event: SYBFREETRYL / SYBDACTRYL / SYBACT",
        "Internal: SYBNOTIFY, SYBNOTDEMO, SYBCTNOTIFY, SYBFT2PAID, SYBSVCERROR",
      ],
    },
    stop: {
      summary: "After customer outcome and any required internal notifies.",
      details: [],
    },
    suppression: { summary: "Trial approve vs decline exclusive.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "SYB event",
        triggerKind: "event",
        triggerDetail: "Trial / activation / conversion",
        next: "path",
      },
      {
        id: "path",
        kind: "branch",
        label: "Path?",
        branches: [
          {
            id: "trial-ok",
            label: "Trial active",
            condition: "SYBFREETRYL",
            next: "trial",
            tone: "success",
          },
          {
            id: "trial-no",
            label: "Trial declined",
            condition: "SYBDACTRYL",
            next: "declined",
            tone: "danger",
          },
          {
            id: "act",
            label: "Paid activation",
            condition: "SYBACT",
            next: "activate",
            tone: "success",
          },
          {
            id: "err",
            label: "Service error",
            condition: "SYBSVCERROR",
            next: "error",
            tone: "danger",
          },
        ],
      },
      {
        id: "trial",
        kind: "email",
        label: "Free trial active",
        emailKey: "SYBFREETRYL",
        subject: "Free Trial Activated! Log Into Your Soundtrack Account Now",
        next: "ops-trial",
      },
      {
        id: "declined",
        kind: "email",
        label: "Trial declined",
        emailKey: "SYBDACTRYL",
        subject: "We Couldn't Approve Your Soundtrack Free Trial",
        next: "exit",
      },
      {
        id: "ops-trial",
        kind: "email",
        label: "Internal: trial tasks",
        emailKey: "SYBNOTIFY",
        subject: "SYB free-trial activation task",
        note: "Also SYBNOTDEMO on create",
        next: "exit",
      },
      {
        id: "activate",
        kind: "email",
        label: "Service activation",
        emailKey: "SYBACT",
        subject: "Welcome! Your Soundtrack Music Subscription Is Ready",
        next: "ops-convert",
      },
      {
        id: "ops-convert",
        kind: "email",
        label: "Internal: conversion",
        emailKey: "SYBFT2PAID",
        subject: "Trial converted to paid",
        note: "Also SYBCTNOTIFY conversion task",
        next: "exit",
      },
      {
        id: "error",
        kind: "email",
        label: "Internal: SYB error",
        emailKey: "SYBSVCERROR",
        subject: "SYB activation error",
        next: "exit-err",
      },
      { id: "exit", kind: "exit", label: "SYB path complete", exitTone: "success" },
      { id: "exit-err", kind: "exit", label: "Ops resolving", exitTone: "danger" },
    ],
    emails: [
      {
        key: "SYBFREETRYL",
        name: "SYB - Free Trial",
        subject: "Free Trial Activated! Log Into Your Soundtrack Account Now",
        purpose: "SYB free trial active",
        trigger: "event",
        apps: ["CRM"],
        step: 1,
      },
      {
        key: "SYBDACTRYL",
        name: "SYB free trial declined",
        subject: "We Couldn't Approve Your Soundtrack Free Trial",
        purpose: "SYB trial declined",
        trigger: "event",
        apps: ["CRM"],
      },
      {
        key: "SYBACT",
        name: "SYB service activation",
        subject: "Welcome! Your Soundtrack Music Subscription Is Ready",
        purpose: "Activation confirmation",
        trigger: "event",
        apps: [
          "CRM",
          "CustomerCommunications",
          "ActivateOnDelivery",
          "DM_Store",
          "PaymentStatusSync",
          "SMS.DM_CRM.ServiceStatusProcessor",
        ],
        step: 1,
      },
      {
        key: "SYBNOTIFY",
        name: "SYB trial activation task",
        subject: "SYB free-trial activation task",
        purpose: "Internal trial activation task",
        trigger: "event",
        apps: ["CRM"],
      },
      {
        key: "SYBNOTDEMO",
        name: "SYB trial created (ops)",
        subject: "SYB free-trial account created",
        purpose: "Internal — trial account created",
        trigger: "event",
        apps: ["CRM"],
      },
      {
        key: "SYBCTNOTIFY",
        name: "SYB conversion task",
        subject: "Conversion task notification",
        purpose: "Internal conversion task",
        trigger: "event",
        apps: ["CRM"],
      },
      {
        key: "SYBFT2PAID",
        name: "Trial→paid conversion",
        subject: "Trial converted to paid",
        purpose: "Internal conversion notify",
        trigger: "event",
        apps: ["CRM"],
      },
      {
        key: "SYBSVCERROR",
        name: "SYB activation error",
        subject: "SYB activation error",
        purpose: "Internal activation error",
        trigger: "event",
        apps: ["CRM"],
      },
    ],
  },

  {
    id: "demo-messaging-welcome",
    sequenceKey: "Support.DemoMessaging",
    name: "Demo Messaging Welcome",
    businessProcess: "Demo messaging portal credentials",
    departmentSlug: "customers",
    processType: "trigger",
    summary: "Welcome new customers with demo messaging portal credentials (MsgDemoWlc).",
    sourceJobs: ["CRM"],
    enrollment: {
      summary: "Demo messaging credentials issued.",
      details: [],
    },
    start: {
      summary: "Demo messaging account created.",
      triggers: ["Event: MsgDemoWlc"],
    },
    stop: {
      summary: "After welcome email sends.",
      details: [],
    },
    suppression: { summary: "Transactional.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Demo messaging account",
        triggerKind: "event",
        triggerDetail: "MsgDemoWlc",
        next: "demo",
      },
      {
        id: "demo",
        kind: "email",
        label: "Demo messaging welcome",
        emailKey: "MsgDemoWlc",
        subject: "[Login Details Inside] Dynamic Media Demo Messaging Portal",
        next: "exit",
      },
      { id: "exit", kind: "exit", label: "Credentials sent", exitTone: "success" },
    ],
    emails: [
      {
        key: "MsgDemoWlc",
        name: "Welcome to Dynamic Media Demo Messaging Portal!",
        subject: "[Login Details Inside] Dynamic Media Demo Messaging Portal",
        purpose: "Demo messaging credentials",
        trigger: "event",
        apps: ["CRM"],
      },
    ],
  },

  {
    id: "parts-support-links",
    sequenceKey: "Support.PartsLinks",
    name: "Parts Support Links",
    businessProcess: "Manual parts / support info send",
    departmentSlug: "customers",
    processType: "manual",
    summary: "Agent sends support information and links for a specific part (SNDPARTLINKS).",
    sourceJobs: ["CRM"],
    enrollment: {
      summary: "Agent selects a part/customer context and sends support links.",
      details: [],
    },
    start: {
      summary: "Agent initiates send.",
      triggers: ["Manual: SNDPARTLINKS"],
    },
    stop: {
      summary: "After support links email sends.",
      details: [],
    },
    suppression: { summary: "Manual — agent controlled.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Agent sends parts links",
        triggerKind: "manual",
        triggerDetail: "SNDPARTLINKS",
        next: "parts",
      },
      {
        id: "parts",
        kind: "email",
        label: "Parts support links",
        emailKey: "SNDPARTLINKS",
        subject: "Support Info for @PartName@",
        next: "exit",
      },
      { id: "exit", kind: "exit", label: "Links sent", exitTone: "success" },
    ],
    emails: [
      {
        key: "SNDPARTLINKS",
        name: "Support info / parts links",
        subject: "Support Info for @PartName@",
        purpose: "Manual parts support links",
        trigger: "manual",
        apps: ["CRM"],
      },
    ],
  },

  {
    id: "exit-survey",
    sequenceKey: "Support.ExitSurvey",
    name: "Exit Survey",
    businessProcess: "Exit survey invite → completion task",
    departmentSlug: "customers",
    processType: "trigger",
    summary:
      "Invite customer to exit survey (SURVEYINV); when completed, internal survey manager task (SURVEYCMPLT).",
    sourceJobs: ["CRM", "SurveyBuilder"],
    enrollment: {
      summary: "Customer enters exit / survey flow.",
      details: ["Customer invite + internal completion companion."],
    },
    start: {
      summary: "Exit survey invitation event.",
      triggers: ["Event: SURVEYINV"],
    },
    stop: {
      summary: "After invite, and after completion task if survey is finished.",
      details: [],
    },
    suppression: { summary: "One invite per exit event.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Exit survey triggered",
        triggerKind: "event",
        triggerDetail: "SURVEYINV",
        note: "CRM",
        next: "survey",
      },
      {
        id: "survey",
        kind: "email",
        label: "Exit survey invite",
        emailKey: "SURVEYINV",
        subject: "We'd Love Your Feedback",
        next: "completed-gate",
      },
      {
        id: "completed-gate",
        kind: "branch",
        label: "Survey completed?",
        branches: [
          {
            id: "yes",
            label: "Completed",
            condition: "Respondent finishes survey",
            next: "survey-done",
            tone: "success",
          },
          {
            id: "no",
            label: "No response",
            condition: "Survey not completed",
            next: "exit-open",
            tone: "neutral",
          },
        ],
      },
      {
        id: "survey-done",
        kind: "email",
        label: "Internal: survey completed",
        emailKey: "SURVEYCMPLT",
        subject: "Survey completion task",
        note: "Internal staff · SurveyBuilder",
        next: "exit-done",
      },
      {
        id: "exit-done",
        kind: "exit",
        label: "Survey closed",
        exitTone: "success",
      },
      {
        id: "exit-open",
        kind: "exit",
        label: "Invite sent — awaiting response",
        exitTone: "neutral",
      },
    ],
    emails: [
      {
        key: "SURVEYINV",
        name: "Exit Survey",
        subject: "We'd Love Your Feedback",
        purpose: "Exit survey invite",
        trigger: "event",
        apps: ["CRM"],
        step: 1,
      },
      {
        key: "SURVEYCMPLT",
        name: "Survey completion task",
        subject: "Survey completion task",
        purpose: "Internal — survey completed",
        trigger: "event",
        apps: ["SurveyBuilder"],
        step: 2,
      },
    ],
  },
];
