import type { WorkflowDefinition } from "./types";

/**
 * Technician / Dealer — each business process is its own workflow.
 * Product variants (DMX / Play / SXM) stay as branches inside one process.
 */

export const DEALER_WORKFLOWS: WorkflowDefinition[] = [
  {
    id: "dealer-onboarding",
    sequenceKey: "Portal.Dealer.Onboarding",
    name: "Dealer Onboarding",
    businessProcess: "Dealer invite → portal welcome → signup complete",
    departmentSlug: "technician-dealer",
    processType: "trigger",
    summary:
      "Invite dealer (DEALERINV) → Dealer Portal welcome by model (PrtDlrWlcCM / PrtDlrWlcDB) → internal signup complete (DLRSGNCMPLT). Customer-facing dealer signup mail lives in Customers → Dealer Signup.",
    sourceJobs: ["CRM", "CustomerCommunications", "DM_Store", "DealerSignup"],
    enrollment: {
      summary: "New dealer partner entering DealerSignup / Dealer Portal.",
      details: ["Welcome variant by commission vs direct-bill model."],
    },
    start: {
      summary: "Dealer invitation created.",
      triggers: ["Event: DEALERINV"],
    },
    stop: {
      summary: "After welcome (and signup-complete if it fires).",
      details: [],
    },
    suppression: {
      summary: "One welcome variant per dealer model.",
      details: [],
    },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Dealer invited",
        triggerKind: "event",
        triggerDetail: "DEALERINV",
        note: "CRM",
        next: "inv",
      },
      {
        id: "inv",
        kind: "email",
        label: "Dealer invitation",
        emailKey: "DEALERINV",
        subject: "Your Dynamic Media Dealer Invitation",
        next: "welcome-model",
      },
      {
        id: "welcome-model",
        kind: "branch",
        label: "Dealer model?",
        branches: [
          {
            id: "cm",
            label: "Commission",
            condition: "PrtDlrWlcCM",
            next: "wlc-cm",
            tone: "neutral",
          },
          {
            id: "db",
            label: "Direct bill",
            condition: "PrtDlrWlcDB",
            next: "wlc-db",
            tone: "neutral",
          },
        ],
      },
      {
        id: "wlc-cm",
        kind: "email",
        label: "Commission dealer welcome",
        emailKey: "PrtDlrWlcCM",
        subject: "Welcome to Dynamic Media!",
        next: "complete-gate",
      },
      {
        id: "wlc-db",
        kind: "email",
        label: "Direct-bill dealer welcome",
        emailKey: "PrtDlrWlcDB",
        subject: "Welcome to Dynamic Media!",
        next: "complete-gate",
      },
      {
        id: "complete-gate",
        kind: "branch",
        label: "Signup finished?",
        branches: [
          {
            id: "yes",
            label: "Yes",
            condition: "DealerSignup complete",
            next: "complete",
            tone: "success",
          },
          {
            id: "no",
            label: "Pending",
            condition: "Still in progress",
            next: "exit-pending",
            tone: "neutral",
          },
        ],
      },
      {
        id: "complete",
        kind: "email",
        label: "Internal: signup complete",
        emailKey: "DLRSGNCMPLT",
        subject: "Dealer Signup completed",
        note: "Internal staff",
        next: "exit-done",
      },
      {
        id: "exit-done",
        kind: "exit",
        label: "Dealer onboarded",
        exitTone: "success",
      },
      {
        id: "exit-pending",
        kind: "exit",
        label: "Awaiting signup",
        exitTone: "neutral",
      },
    ],
    emails: [
      {
        key: "DEALERINV",
        name: "Dealer invitation",
        subject: "Your Dynamic Media Dealer Invitation",
        purpose: "Invite new dealer partner",
        trigger: "event",
        apps: ["CRM"],
        step: 1,
      },
      {
        key: "PrtDlrWlcCM",
        name: "Commission dealer welcome",
        subject: "Welcome to Dynamic Media!",
        purpose: "Commission-model Dealer Portal welcome",
        trigger: "event",
        apps: ["CRM"],
        step: 2,
      },
      {
        key: "PrtDlrWlcDB",
        name: "Direct-bill dealer welcome",
        subject: "Welcome to Dynamic Media!",
        purpose: "Direct-bill Dealer Portal welcome",
        trigger: "event",
        apps: ["CRM"],
        step: 2,
      },
      {
        key: "DLRSGNCMPLT",
        name: "Dealer Signup completed",
        subject: "Dealer Signup completed",
        purpose: "Internal — dealer signup finished",
        trigger: "event",
        apps: ["DealerSignup"],
        step: 3,
      },
    ],
  },

  {
    id: "dealer-portal-password",
    sequenceKey: "Portal.Dealer.PasswordReset",
    name: "Dealer Portal Password Reset",
    businessProcess: "Dealer portal password reset",
    departmentSlug: "technician-dealer",
    processType: "trigger",
    summary: "On-demand dealer portal password reset (PrtDlrPR).",
    sourceJobs: ["CRM", "CustomerCommunications", "DM_Store", "CustomerPortal"],
    enrollment: {
      summary: "Dealer requests or is issued a portal password reset.",
      details: [],
    },
    start: {
      summary: "Dealer password reset requested.",
      triggers: ["Event: PrtDlrPR"],
    },
    stop: {
      summary: "After reset email sends.",
      details: [],
    },
    suppression: { summary: "Transactional.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Password reset requested",
        triggerKind: "event",
        triggerDetail: "PrtDlrPR",
        next: "pr",
      },
      {
        id: "pr",
        kind: "email",
        label: "Dealer password reset",
        emailKey: "PrtDlrPR",
        subject: "Dynamic Media Customer Portal - Password Reset",
        next: "exit",
      },
      { id: "exit", kind: "exit", label: "Reset sent", exitTone: "success" },
    ],
    emails: [
      {
        key: "PrtDlrPR",
        name: "Dealer portal password",
        subject: "Dynamic Media Customer Portal - Password Reset",
        purpose: "Dealer portal password reset",
        trigger: "event",
        apps: ["CRM", "CustomerCommunications", "DM_Store", "CustomerPortal"],
      },
    ],
  },

  {
    id: "dealer-referral-update",
    sequenceKey: "Dealer.Referral.Status",
    name: "Dealer Referral Status",
    businessProcess: "Referral status update to dealer",
    departmentSlug: "technician-dealer",
    processType: "trigger",
    summary: "Notify dealer when a referral status changes (DealerUpdat).",
    sourceJobs: ["CRM"],
    enrollment: {
      summary: "Dealer has an open referral whose status changes.",
      details: [],
    },
    start: {
      summary: "Referral status updated.",
      triggers: ["Event: DealerUpdat"],
    },
    stop: {
      summary: "After status email sends.",
      details: [],
    },
    suppression: { summary: "One notify per status change.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Referral status changed",
        triggerKind: "event",
        triggerDetail: "DealerUpdat",
        next: "upd",
      },
      {
        id: "upd",
        kind: "email",
        label: "Referral status update",
        emailKey: "DealerUpdat",
        subject: "Update On Your Dynamic Media Referral",
        next: "exit",
      },
      { id: "exit", kind: "exit", label: "Dealer notified", exitTone: "success" },
    ],
    emails: [
      {
        key: "DealerUpdat",
        name: "Referral status update",
        subject: "Update On Your Dynamic Media Referral",
        purpose: "Referral status to dealer",
        trigger: "event",
        apps: ["CRM"],
      },
    ],
  },

  {
    id: "tech-service-activation",
    sequenceKey: "Service.Tech.Activate",
    name: "Tech Service Activation",
    businessProcess: "Technician network / SXM activation",
    departmentSlug: "technician-dealer",
    processType: "trigger",
    summary:
      "Tech notify to activate DMX, Play, SXM internet, or SXM satellite on the scheduled date.",
    sourceJobs: ["CRM"],
    enrollment: {
      summary: "Service scheduled for activation today.",
      details: ["Branch by product / network."],
    },
    start: {
      summary: "Activation scheduled for today.",
      triggers: ["Event: ACTDMX / ACTPLAY / ACTSXIR / ACTSXM"],
    },
    stop: {
      summary: "After activation email sends.",
      details: [],
    },
    suppression: {
      summary: "One activation email per radio/service.",
      details: [],
    },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Activation scheduled",
        triggerKind: "event",
        triggerDetail: "ACT* for scheduled date",
        note: "CRM",
        next: "product",
      },
      {
        id: "product",
        kind: "branch",
        label: "Which product?",
        branches: [
          { id: "dmx", label: "DMX", condition: "ACTDMX", next: "act-dmx", tone: "neutral" },
          { id: "play", label: "Play", condition: "ACTPLAY", next: "act-play", tone: "neutral" },
          { id: "sxir", label: "SXM internet", condition: "ACTSXIR", next: "act-sxir", tone: "neutral" },
          { id: "sxm", label: "SXM satellite", condition: "ACTSXM", next: "act-sxm", tone: "neutral" },
        ],
      },
      {
        id: "act-dmx",
        kind: "email",
        label: "DMX activation",
        emailKey: "ACTDMX",
        subject: "[Alert] Network Activation… Scheduled Today",
        next: "exit",
      },
      {
        id: "act-play",
        kind: "email",
        label: "Play activation",
        emailKey: "ACTPLAY",
        subject: "[Alert] Network Activation… Scheduled Today",
        next: "exit",
      },
      {
        id: "act-sxir",
        kind: "email",
        label: "SXM internet activate",
        emailKey: "ACTSXIR",
        subject: "SXM internet activation",
        next: "exit",
      },
      {
        id: "act-sxm",
        kind: "email",
        label: "SXM satellite activate",
        emailKey: "ACTSXM",
        subject: "SXM satellite activation",
        next: "exit",
      },
      { id: "exit", kind: "exit", label: "Tech notified", exitTone: "success" },
    ],
    emails: [
      { key: "ACTDMX", name: "DMX Activation", subject: "[Alert] Network Activation… Scheduled Today", purpose: "Tech: activate DMX", trigger: "event", apps: ["CRM"] },
      { key: "ACTPLAY", name: "Play Network Activation", subject: "[Alert] Network Activation… Scheduled Today", purpose: "Tech: activate Play", trigger: "event", apps: ["CRM"] },
      { key: "ACTSXIR", name: "SXM internet activate", subject: "SXM internet activation", purpose: "Tech: activate SXM internet", trigger: "event", apps: ["CRM"] },
      { key: "ACTSXM", name: "SXM satellite activate", subject: "SXM satellite activation", purpose: "Tech: activate SXM satellite", trigger: "event", apps: ["CRM"] },
    ],
  },

  {
    id: "tech-free-trial-credentials",
    sequenceKey: "Service.Tech.FreeTrial",
    name: "Tech Free Trial Credentials",
    businessProcess: "SXM internet free-trial credentials to dealer",
    departmentSlug: "technician-dealer",
    processType: "trigger",
    summary:
      "Issue free-trial credentials to dealer support (FREETRIAL), or reissue (RESENDTRIAL).",
    sourceJobs: ["CRM"],
    enrollment: {
      summary: "Dealer needs internet free-trial credentials for a customer.",
      details: [],
    },
    start: {
      summary: "Trial credential request or resend.",
      triggers: ["Event: FREETRIAL", "Event: RESENDTRIAL"],
    },
    stop: {
      summary: "After credential email sends.",
      details: [],
    },
    suppression: { summary: "One credential send per request.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Trial credential request",
        triggerKind: "event",
        triggerDetail: "FREETRIAL or RESENDTRIAL",
        next: "which",
      },
      {
        id: "which",
        kind: "branch",
        label: "Issue or resend?",
        branches: [
          {
            id: "new",
            label: "New issue",
            condition: "FREETRIAL",
            next: "ft",
            tone: "neutral",
          },
          {
            id: "resend",
            label: "Resend",
            condition: "RESENDTRIAL",
            next: "rft",
            tone: "neutral",
          },
        ],
      },
      {
        id: "ft",
        kind: "email",
        label: "Free trial to dealer",
        emailKey: "FREETRIAL",
        subject: "Internet free-trial credentials",
        next: "exit",
      },
      {
        id: "rft",
        kind: "email",
        label: "Resend trial",
        emailKey: "RESENDTRIAL",
        subject: "Resend free-trial credentials",
        next: "exit",
      },
      { id: "exit", kind: "exit", label: "Credentials sent", exitTone: "success" },
    ],
    emails: [
      { key: "FREETRIAL", name: "SXM trial to dealer support", subject: "Internet free-trial credentials", purpose: "Trial credential request to dealer", trigger: "event", apps: ["CRM"] },
      { key: "RESENDTRIAL", name: "Resend trial to dealer", subject: "Resend free-trial credentials", purpose: "Reissue trial credentials", trigger: "event", apps: ["CRM"] },
    ],
  },

  {
    id: "tech-service-reactivation",
    sequenceKey: "Service.Tech.Reactivate",
    name: "Tech Service Reactivation",
    businessProcess: "Technician SXM reactivation",
    departmentSlug: "technician-dealer",
    processType: "trigger",
    summary: "Reactivate SXM internet or satellite using existing credentials / ESN.",
    sourceJobs: ["CRM"],
    enrollment: {
      summary: "Service reactivation requested for tech.",
      details: [],
    },
    start: {
      summary: "Reactivation event.",
      triggers: ["Event: REACTSXIR", "Event: REACTSXM"],
    },
    stop: {
      summary: "After reactivation email sends.",
      details: [],
    },
    suppression: { summary: "One per radio.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Reactivation requested",
        triggerKind: "event",
        triggerDetail: "REACTSXIR / REACTSXM",
        next: "product",
      },
      {
        id: "product",
        kind: "branch",
        label: "Which product?",
        branches: [
          { id: "sxir", label: "SXM internet", condition: "REACTSXIR", next: "re-sxir", tone: "neutral" },
          { id: "sxm", label: "SXM satellite", condition: "REACTSXM", next: "re-sxm", tone: "neutral" },
        ],
      },
      {
        id: "re-sxir",
        kind: "email",
        label: "Reactivate SXM-IR",
        emailKey: "REACTSXIR",
        subject: "SXM internet reactivation",
        next: "exit",
      },
      {
        id: "re-sxm",
        kind: "email",
        label: "Reactivate SXM sat",
        emailKey: "REACTSXM",
        subject: "SXM satellite reactivation",
        next: "exit",
      },
      { id: "exit", kind: "exit", label: "Tech notified", exitTone: "success" },
    ],
    emails: [
      { key: "REACTSXIR", name: "SXM internet reactivate", subject: "SXM internet reactivation", purpose: "Tech: reactivate SXM internet", trigger: "event", apps: ["CRM"] },
      { key: "REACTSXM", name: "SXM satellite reactivate", subject: "SXM satellite reactivation", purpose: "Tech: reactivate satellite", trigger: "event", apps: ["CRM"] },
    ],
  },

  {
    id: "tech-receiver-swap",
    sequenceKey: "Service.Tech.ReceiverSwap",
    name: "SXM Receiver Swap",
    businessProcess: "Satellite receiver ESN swap",
    departmentSlug: "technician-dealer",
    processType: "trigger",
    summary: "Tech request to swap SXM satellite receiver from old ESN to new ESN (BXSWPSXM).",
    sourceJobs: ["CRM"],
    enrollment: {
      summary: "Receiver swap needed for a satellite customer.",
      details: [],
    },
    start: {
      summary: "Receiver swap event.",
      triggers: ["Event: BXSWPSXM"],
    },
    stop: {
      summary: "After swap email sends.",
      details: [],
    },
    suppression: { summary: "One per swap request.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Receiver swap requested",
        triggerKind: "event",
        triggerDetail: "BXSWPSXM",
        next: "swap",
      },
      {
        id: "swap",
        kind: "email",
        label: "Receiver swap",
        emailKey: "BXSWPSXM",
        subject: "SXM receiver swap",
        next: "exit",
      },
      { id: "exit", kind: "exit", label: "Tech notified", exitTone: "success" },
    ],
    emails: [
      { key: "BXSWPSXM", name: "SXM receiver swap", subject: "SXM receiver swap", purpose: "Tech: swap satellite receiver ESN", trigger: "event", apps: ["CRM"] },
    ],
  },

  {
    id: "tech-service-deactivation",
    sequenceKey: "Service.Tech.Deactivate",
    name: "Tech Service Deactivation",
    businessProcess: "Technician SXM deactivation",
    departmentSlug: "technician-dealer",
    processType: "trigger",
    summary: "Tech notify to deactivate SXM internet or satellite service.",
    sourceJobs: ["CRM"],
    enrollment: {
      summary: "Service deactivation requested for tech.",
      details: [],
    },
    start: {
      summary: "Deactivation event.",
      triggers: ["Event: DEACTSXIR", "Event: DEACTSXM"],
    },
    stop: {
      summary: "After deactivation email sends.",
      details: [],
    },
    suppression: { summary: "One per radio.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Deactivation requested",
        triggerKind: "event",
        triggerDetail: "DEACTSXIR / DEACTSXM",
        next: "product",
      },
      {
        id: "product",
        kind: "branch",
        label: "Which product?",
        branches: [
          { id: "sxir", label: "SXM internet", condition: "DEACTSXIR", next: "de-sxir", tone: "neutral" },
          { id: "sxm", label: "SXM satellite", condition: "DEACTSXM", next: "de-sxm", tone: "neutral" },
        ],
      },
      {
        id: "de-sxir",
        kind: "email",
        label: "Deactivate SXM-IR",
        emailKey: "DEACTSXIR",
        subject: "SXM internet deactivation",
        next: "exit",
      },
      {
        id: "de-sxm",
        kind: "email",
        label: "Deactivate SXM sat",
        emailKey: "DEACTSXM",
        subject: "SXM satellite deactivation",
        next: "exit",
      },
      { id: "exit", kind: "exit", label: "Tech notified", exitTone: "danger" },
    ],
    emails: [
      { key: "DEACTSXIR", name: "SXM internet deactivate", subject: "SXM internet deactivation", purpose: "Tech: deactivate SXM internet", trigger: "event", apps: ["CRM"] },
      { key: "DEACTSXM", name: "SXM satellite deactivate", subject: "SXM satellite deactivation", purpose: "Tech: deactivate SXM satellite", trigger: "event", apps: ["CRM"] },
    ],
  },
];
