import type { WorkflowDefinition } from "./types";

/**
 * Encore / PSAV VIP program — customer portal emails + internal companions
 * (e.g. PSAVFDBKSBMT) share journeys with customer-facing twins.
 */

export const ENCORE_WORKFLOWS: WorkflowDefinition[] = [
  {
    id: "encore-portal-activation",
    sequenceKey: "Portal.PSAV.LoginNudge",
    name: "Portal Activation & Login Nudge",
    businessProcess: "Encore portal invite → login ladder → staff escalate",
    departmentSlug: "encore",
    processType: "timed",
    summary:
      "VIP Encore journey: invite new portal user, timed login reminders (Rem1→2→3), then internal no-login alert. New site assignment can fire in parallel.",
    sourceJobs: ["VipHandler", "CustomerPortal"],
    enrollment: {
      summary: "New Encore / PSAV site contact invited to the music portal.",
      details: [
        "Customer-facing invite + nudges; PSAVUSERFAIL is internal escalate.",
        "PSAVNEWSITE may fire independently when a location is added.",
      ],
    },
    start: {
      summary: "New Encore portal user created / invited.",
      triggers: [
        "Event: PSAVNEWUSER",
        "Scheduled: VipHandler Rem1→Rem2→Rem3→FAIL",
        "Parallel event: PSAVNEWSITE",
      ],
    },
    stop: {
      summary: "User logs in, or staff FAIL alert after final reminder.",
      details: [
        "STOP on first successful portal login.",
        "STOP after PSAVUSERFAIL (staff owns outreach).",
      ],
    },
    suppression: {
      summary: "One nudge ladder per contact until login or FAIL.",
      details: ["Day gaps TBD with Encore SME (VipHandler)."],
    },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "New Encore portal user",
        triggerKind: "event",
        triggerDetail: "PSAVNEWUSER invite",
        note: "CustomerPortal · VipHandler",
        next: "invite",
      },
      {
        id: "invite",
        kind: "email",
        label: "Portal invitation",
        emailKey: "PSAVNEWUSER",
        subject: "Welcome to the Dynamic Media Music Portal",
        next: "site-gate",
      },
      {
        id: "site-gate",
        kind: "branch",
        label: "New site assigned?",
        branches: [
          {
            id: "site-yes",
            label: "Yes — notify",
            condition: "Location added to subscription",
            next: "new-site",
            tone: "success",
          },
          {
            id: "site-no",
            label: "Skip",
            condition: "No new site event",
            next: "check0",
            tone: "neutral",
          },
        ],
      },
      {
        id: "new-site",
        kind: "email",
        label: "New location notice",
        emailKey: "PSAVNEWSITE",
        subject: "A New Location Has Been Added to Your Subscription",
        next: "check0",
      },
      {
        id: "check0",
        kind: "branch",
        label: "Logged in after invite?",
        branches: [
          {
            id: "yes0",
            label: "Yes — activated",
            condition: "User logged in",
            next: "exit-ok",
            tone: "success",
          },
          {
            id: "no0",
            label: "No — nudge",
            condition: "Still no login",
            next: "wait1",
            tone: "danger",
          },
        ],
      },
      {
        id: "wait1",
        kind: "delay",
        label: "Wait (days TBD)",
        note: "Invite → Rem1 — VipHandler",
        next: "rem1",
      },
      {
        id: "rem1",
        kind: "email",
        label: "Login reminder 1",
        emailKey: "PSAVUSERREM1",
        subject: "Welcome! Activate Your Music Portal Account",
        next: "check1",
      },
      {
        id: "check1",
        kind: "branch",
        label: "Logged in?",
        branches: [
          {
            id: "yes1",
            label: "Yes",
            condition: "User logged in",
            next: "exit-ok",
            tone: "success",
          },
          {
            id: "no1",
            label: "No — continue",
            condition: "Still no login",
            next: "wait2",
            tone: "danger",
          },
        ],
      },
      {
        id: "wait2",
        kind: "delay",
        label: "Wait (days TBD)",
        note: "Rem1 → Rem2",
        next: "rem2",
      },
      {
        id: "rem2",
        kind: "email",
        label: "Login reminder 2",
        emailKey: "PSAVUSERREM2",
        subject: "Reminder: Please Activate Your Music Portal Account",
        next: "check2",
      },
      {
        id: "check2",
        kind: "branch",
        label: "Logged in?",
        branches: [
          {
            id: "yes2",
            label: "Yes",
            condition: "User logged in",
            next: "exit-ok",
            tone: "success",
          },
          {
            id: "no2",
            label: "No — continue",
            condition: "Still no login",
            next: "wait3",
            tone: "danger",
          },
        ],
      },
      {
        id: "wait3",
        kind: "delay",
        label: "Wait (days TBD)",
        note: "Rem2 → Rem3",
        next: "rem3",
      },
      {
        id: "rem3",
        kind: "email",
        label: "Final login reminder",
        emailKey: "PSAVUSERREM3",
        subject: "Final Reminder: Activate Your Music Portal Account",
        next: "check3",
      },
      {
        id: "check3",
        kind: "branch",
        label: "Logged in after final?",
        branches: [
          {
            id: "yes3",
            label: "Yes",
            condition: "User logged in",
            next: "exit-ok",
            tone: "success",
          },
          {
            id: "no3",
            label: "No — escalate staff",
            condition: "Still no login",
            next: "wait-fail",
            tone: "danger",
          },
        ],
      },
      {
        id: "wait-fail",
        kind: "delay",
        label: "Wait (~28d TBD)",
        note: "Catalog notes ~28d after invite — confirm",
        next: "fail",
      },
      {
        id: "fail",
        kind: "email",
        label: "Staff: no login alert",
        emailKey: "PSAVUSERFAIL",
        subject: "Site Contact | No Login or Response",
        note: "Internal escalate — Encore ops",
        next: "exit-fail",
      },
      {
        id: "exit-ok",
        kind: "exit",
        label: "Portal activated",
        exitTone: "success",
      },
      {
        id: "exit-fail",
        kind: "exit",
        label: "Staff owning outreach",
        exitTone: "danger",
      },
    ],
    emails: [
      {
        key: "PSAVNEWUSER",
        name: "Your Invitation to the Dynamic Media Music Portal",
        subject: "Welcome to the Dynamic Media Music Portal",
        purpose: "Encore new user invite",
        trigger: "event",
        apps: ["CustomerPortal"],
        step: 1,
      },
      {
        key: "PSAVNEWSITE",
        name: "A new location has been added to your profile",
        subject: "A New Location Has Been Added to Your Subscription",
        purpose: "Site assignment confirmation",
        trigger: "event",
        apps: ["CustomerPortal"],
      },
      {
        key: "PSAVUSERREM1",
        name: "Reminder to log in to the Dynamic Media Music Portal",
        subject: "Welcome! Activate Your Music Portal Account",
        purpose: "Login reminder 1",
        trigger: "scheduled",
        apps: ["VipHandler"],
        step: 2,
      },
      {
        key: "PSAVUSERREM2",
        name: "2nd Reminder | Please log in to the Dynamic Media Music Portal",
        subject: "Reminder: Please Activate Your Music Portal Account",
        purpose: "Login reminder 2",
        trigger: "scheduled",
        apps: ["VipHandler"],
        step: 3,
      },
      {
        key: "PSAVUSERREM3",
        name: "Final Reminder | Please log in to the Dynamic Media Music Portal",
        subject: "Final Reminder: Activate Your Music Portal Account",
        purpose: "Final login reminder",
        trigger: "scheduled",
        apps: ["VipHandler"],
        step: 4,
      },
      {
        key: "PSAVUSERFAIL",
        name: "Site Contact | No Login or Response",
        subject: "Site Contact | No Login or Response",
        purpose: "Internal — no login after nudges",
        trigger: "scheduled",
        apps: ["VipHandler"],
        step: 5,
      },
    ],
    openQuestions: ["Exact VipHandler day gaps and FAIL timing."],
  },

  {
    id: "encore-subscription-end",
    sequenceKey: "Portal.PSAV.SubscriptionEnd",
    name: "Subscription End Ladder",
    businessProcess: "Encore subscription ending warn → ended",
    departmentSlug: "encore",
    processType: "timed",
    summary:
      "Warn before subscription ends (PSAVSUBWARN), then ended notice (PSAVSUBENDED) if not renewed. Timed via VipHandler.",
    sourceJobs: ["VipHandler"],
    enrollment: {
      summary: "Encore subscription entering end-date window.",
      details: [],
    },
    start: {
      summary: "Subscription end window opens.",
      triggers: ["Scheduled: VipHandler PSAVSUBWARN → PSAVSUBENDED"],
    },
    stop: {
      summary: "After ended notice, or if renewed between WARN and ENDED.",
      details: ["STOP if subscription extended after WARN."],
    },
    suppression: {
      summary: "One warn→ended pair per subscription end event.",
      details: ["Day gaps TBD with Encore SME."],
    },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Subscription end window",
        triggerKind: "scheduled",
        triggerDetail: "VipHandler end-date window",
        next: "wait-warn",
      },
      {
        id: "wait-warn",
        kind: "delay",
        label: "Lead time (days TBD)",
        note: "Before PSAVSUBWARN — confirm with Encore SME",
        next: "warn",
      },
      {
        id: "warn",
        kind: "email",
        label: "Subscription ending soon",
        emailKey: "PSAVSUBWARN",
        subject: "Your Music Subscription will be ending soon",
        delayAfter: { days: null, status: "tbd", note: "WARN → ENDED gap" },
        next: "check-renew",
      },
      {
        id: "check-renew",
        kind: "branch",
        label: "Renewed?",
        branches: [
          {
            id: "yes",
            label: "Renewed",
            condition: "Subscription extended",
            next: "exit-ok",
            tone: "success",
          },
          {
            id: "no",
            label: "Still ending",
            condition: "End date reached",
            next: "ended",
            tone: "danger",
          },
        ],
      },
      {
        id: "ended",
        kind: "email",
        label: "Subscription has ended",
        emailKey: "PSAVSUBENDED",
        subject: "Your Music Subscription Has Ended",
        next: "exit-ended",
      },
      {
        id: "exit-ok",
        kind: "exit",
        label: "Renewed — ladder stopped",
        exitTone: "success",
      },
      {
        id: "exit-ended",
        kind: "exit",
        label: "Subscription ended",
        exitTone: "danger",
      },
    ],
    emails: [
      {
        key: "PSAVSUBWARN",
        name: "Your Music Subscription will be ending soon",
        subject: "Your Music Subscription will be ending soon",
        purpose: "Warn before subscription ends",
        trigger: "scheduled",
        apps: ["VipHandler"],
        step: 1,
      },
      {
        key: "PSAVSUBENDED",
        name: "Your Music Subscription Has Ended",
        subject: "Your Music Subscription Has Ended",
        purpose: "Notify subscription ended",
        trigger: "scheduled",
        apps: ["VipHandler"],
        step: 2,
      },
    ],
    openQuestions: ["Exact VipHandler day gaps for WARN → ENDED."],
  },

  {
    id: "encore-service-action",
    sequenceKey: "Portal.PSAV.ServiceAction",
    name: "Service Action Confirmation",
    businessProcess: "Encore service action confirm",
    departmentSlug: "encore",
    processType: "trigger",
    summary:
      "Confirm an Encore portal service action request to the customer (PSAVSVCACTN).",
    sourceJobs: ["CustomerPortal"],
    enrollment: {
      summary: "Service action request confirmed in portal.",
      details: [],
    },
    start: {
      summary: "Service action confirmed.",
      triggers: ["Event: PSAVSVCACTN"],
    },
    stop: {
      summary: "After confirmation email sends.",
      details: [],
    },
    suppression: { summary: "One confirm per request.", details: [] },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Service action confirmed",
        triggerKind: "event",
        triggerDetail: "PSAVSVCACTN",
        note: "CustomerPortal",
        next: "svc",
      },
      {
        id: "svc",
        kind: "email",
        label: "Service action confirmed",
        emailKey: "PSAVSVCACTN",
        subject: "Your @RequestType@ Has Been Confirmed",
        next: "exit",
      },
      {
        id: "exit",
        kind: "exit",
        label: "Customer notified",
        exitTone: "success",
      },
    ],
    emails: [
      {
        key: "PSAVSVCACTN",
        name: "Confirming your service action",
        subject: "Your @RequestType@ Has Been Confirmed",
        purpose: "Encore service action confirmation",
        trigger: "event",
        apps: ["CustomerPortal"],
      },
    ],
  },

  {
    id: "encore-feedback",
    sequenceKey: "Portal.PSAV.Feedback",
    name: "Portal Feedback Loop",
    businessProcess: "Encore portal feedback",
    departmentSlug: "encore",
    processType: "trigger",
    summary:
      "When Encore portal feedback is submitted: internal staff alert (PSAVFDBKSBMT) and customer thank-you (PSAVFDBKCONF).",
    sourceJobs: ["CustomerPortal"],
    enrollment: {
      summary: "User submits Encore portal feedback form.",
      details: ["Customer + internal twin on same event."],
    },
    start: {
      summary: "Feedback form submitted.",
      triggers: ["Event: Portal feedback submitted"],
    },
    stop: {
      summary: "After staff alert and customer thank-you.",
      details: [],
    },
    suppression: {
      summary: "One pair per submission.",
      details: [],
    },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Feedback submitted",
        triggerKind: "event",
        triggerDetail: "Encore portal feedback form",
        next: "staff",
      },
      {
        id: "staff",
        kind: "email",
        label: "Staff feedback alert",
        emailKey: "PSAVFDBKSBMT",
        subject: "@Category@ from Portal Feedback Form",
        note: "Encore / PSAV (internal)",
        next: "customer",
      },
      {
        id: "customer",
        kind: "email",
        label: "Thanks for feedback",
        emailKey: "PSAVFDBKCONF",
        subject: "Thanks! We Received Your Feedback",
        note: "Catalogued under Customers group — VIP companion",
        next: "exit",
      },
      {
        id: "exit",
        kind: "exit",
        label: "Feedback routed",
        exitTone: "success",
      },
    ],
    emails: [
      {
        key: "PSAVFDBKSBMT",
        name: "from Portal Feedback Form",
        subject: "@Category@ from Portal Feedback Form",
        purpose: "Internal — Encore feedback submitted",
        trigger: "event",
        apps: ["CustomerPortal"],
        step: 1,
      },
      {
        key: "PSAVFDBKCONF",
        name: "Your Portal Feedback Form",
        subject: "Thanks! We Received Your Feedback",
        purpose: "Customer thank-you for feedback",
        trigger: "event",
        apps: ["CustomerPortal"],
        step: 2,
      },
    ],
  },
];
