import type { WorkflowDefinition } from "./types";

/**
 * Tim Hortons VIP program — customer store emails + internal companions
 * (NOTFYNEWRENO, SPNOTIFY) live in the same journeys.
 */

export const TIM_HORTONS_WORKFLOWS: WorkflowDefinition[] = [
  {
    id: "th-fulfillment-lifecycle",
    sequenceKey: "Fulfillment.TimHortons",
    name: "Store Fulfillment Lifecycle",
    businessProcess: "TH New & Reno fulfillment",
    departmentSlug: "tim-hortons",
    processType: "trigger",
    summary:
      "VIP Tim Hortons journey: order confirm (EN/FR) → internal New Reno + install notifies → portal welcome → setup guide → ship → players online vs offline help. Locale twins branch EN/FR.",
    sourceJobs: [
      "DM_Store",
      "CustomerCommunications",
      "CRM",
      "OnlineSign",
      "PaymentStatusSync",
    ],
    enrollment: {
      summary: "Tim Hortons store order / New & Reno location entering fulfillment.",
      details: [
        "Customer-facing store emails plus internal ops companions in one journey.",
        "EN xor FR for each locale twin step.",
      ],
    },
    start: {
      summary: "TH music order confirmed.",
      triggers: [
        "Event: Tim Hortons order confirmed (SHOPTHCONF / SHOPTHCONFF)",
        "Internal: NOTFYNEWRENO, SPNOTIFY",
      ],
    },
    stop: {
      summary: "Players confirmed online, or offline help sent for support follow-up.",
      details: [
        "STOP after online confirm or offline help for the store locale.",
        "STOP if order cancelled mid-journey.",
      ],
    },
    suppression: {
      summary: "One active fulfillment journey per store order; EN xor FR per step.",
      details: ["Do not send both locale twins for the same step."],
    },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "TH order placed",
        triggerKind: "event",
        triggerDetail: "Tim Hortons order confirmed",
        next: "locale-order",
      },
      {
        id: "locale-order",
        kind: "branch",
        label: "Order locale?",
        branches: [
          {
            id: "en-o",
            label: "English",
            condition: "EN store",
            next: "order-en",
            tone: "neutral",
          },
          {
            id: "fr-o",
            label: "French",
            condition: "FR store",
            next: "order-fr",
            tone: "neutral",
          },
        ],
      },
      {
        id: "order-en",
        kind: "email",
        label: "Order confirmed (EN)",
        emailKey: "SHOPTHCONF",
        subject: "Your Music Order is Confirmed!",
        next: "internal-reno",
      },
      {
        id: "order-fr",
        kind: "email",
        label: "Order confirmed (FR)",
        emailKey: "SHOPTHCONFF",
        subject: "Magasin de musique de Tim Hortons - Confirmation d'achat",
        next: "internal-reno",
      },
      {
        id: "internal-reno",
        kind: "email",
        label: "Internal: New Reno purchase",
        emailKey: "NOTFYNEWRENO",
        subject: "@Subject@",
        note: "Tim Hortons (internal) companion",
        next: "internal-install",
      },
      {
        id: "internal-install",
        kind: "email",
        label: "Internal: install request",
        emailKey: "SPNOTIFY",
        subject: "@Subject@",
        note: "Tim Hortons (internal) companion",
        next: "locale-welcome",
      },
      {
        id: "locale-welcome",
        kind: "branch",
        label: "Welcome locale?",
        branches: [
          {
            id: "en-w",
            label: "English",
            condition: "EN",
            next: "welcome-en",
            tone: "neutral",
          },
          {
            id: "fr-w",
            label: "French",
            condition: "FR",
            next: "welcome-fr",
            tone: "neutral",
          },
        ],
      },
      {
        id: "welcome-en",
        kind: "email",
        label: "Portal welcome (EN)",
        emailKey: "PRTLTHWLCM",
        subject: "Welcome to the Dynamic Media Portal!",
        next: "locale-setup",
      },
      {
        id: "welcome-fr",
        kind: "email",
        label: "Portal welcome (FR)",
        emailKey: "PRTLTHWLCMFR",
        subject: "Bienvenue sur le portail Dynamic Media!",
        next: "locale-setup",
      },
      {
        id: "locale-setup",
        kind: "branch",
        label: "Setup locale?",
        branches: [
          {
            id: "en-s",
            label: "English",
            condition: "EN",
            next: "setup-en",
            tone: "neutral",
          },
          {
            id: "fr-s",
            label: "French",
            condition: "FR",
            next: "setup-fr",
            tone: "neutral",
          },
        ],
      },
      {
        id: "setup-en",
        kind: "email",
        label: "Setup guide (EN)",
        emailKey: "THGETSTART",
        subject: "[Important] Music Player Setup Guide – Save This Email",
        next: "remote",
      },
      {
        id: "setup-fr",
        kind: "email",
        label: "Setup guide (FR)",
        emailKey: "THGETSTARTFR",
        subject:
          "[Important] Guide de configuration du lecteur musical – Conservez ce courriel",
        next: "remote",
      },
      {
        id: "remote",
        kind: "email",
        label: "Remote control codes",
        emailKey: "THREMOTECODE",
        subject: "Music Control — No App Required",
        next: "ship",
      },
      {
        id: "ship",
        kind: "email",
        label: "Order shipped",
        emailKey: "THOrderShip",
        subject: "Your Music Order Has Shipped!",
        next: "online-status",
      },
      {
        id: "online-status",
        kind: "branch",
        label: "Players online?",
        branches: [
          {
            id: "online",
            label: "Online",
            condition: "Players reported online",
            next: "locale-online",
            tone: "success",
          },
          {
            id: "offline",
            label: "Not online",
            condition: "Players not online",
            next: "locale-help",
            tone: "danger",
          },
        ],
      },
      {
        id: "locale-online",
        kind: "branch",
        label: "Locale?",
        branches: [
          {
            id: "en-on",
            label: "English",
            condition: "EN",
            next: "online-en",
            tone: "neutral",
          },
          {
            id: "fr-on",
            label: "French",
            condition: "FR",
            next: "online-fr",
            tone: "neutral",
          },
        ],
      },
      {
        id: "online-en",
        kind: "email",
        label: "Players online (EN)",
        emailKey: "THPLONLINE",
        subject: "Your Music Players are Online!",
        next: "exit-ok",
      },
      {
        id: "online-fr",
        kind: "email",
        label: "Players online (FR)",
        emailKey: "THPLONLINEFR",
        subject: "Vos lecteurs musicaux sont en ligne!",
        next: "exit-ok",
      },
      {
        id: "locale-help",
        kind: "branch",
        label: "Locale?",
        branches: [
          {
            id: "en-h",
            label: "English",
            condition: "EN",
            next: "help-en",
            tone: "neutral",
          },
          {
            id: "fr-h",
            label: "French",
            condition: "FR",
            next: "help-fr",
            tone: "neutral",
          },
        ],
      },
      {
        id: "help-en",
        kind: "email",
        label: "Offline help (EN)",
        emailKey: "THNOTONLINE",
        subject: "Let's Get Your Music Players Online - Need Assistance?",
        next: "exit-help",
      },
      {
        id: "help-fr",
        kind: "email",
        label: "Offline help (FR)",
        emailKey: "THNOTONLINEFR",
        subject: "Mettons vos lecteurs musicaux en ligne — Besoin d'aide?",
        next: "exit-help",
      },
      {
        id: "exit-ok",
        kind: "exit",
        label: "Store live",
        exitTone: "success",
      },
      {
        id: "exit-help",
        kind: "exit",
        label: "Help sent — support follow-up",
        exitTone: "danger",
      },
    ],
    emails: [
      {
        key: "SHOPTHCONF",
        name: "Your Music Order is Confirmed!",
        subject: "Your Music Order is Confirmed!",
        purpose: "TH order confirmed (EN)",
        trigger: "event",
        apps: ["DM_Store", "OnlineSign", "PaymentStatusSync", "CRM"],
        step: 1,
      },
      {
        key: "SHOPTHCONFF",
        name: "Magasin de musique de Tim Hortons - Confirmation d'achat",
        subject: "Magasin de musique de Tim Hortons - Confirmation d'achat",
        purpose: "TH order confirmation (FR)",
        trigger: "event",
        apps: ["DM_Store"],
        step: 1,
      },
      {
        key: "NOTFYNEWRENO",
        name: "Purchase of New Reno soundtrack service",
        subject: "@Subject@",
        purpose: "Internal — New Reno soundtrack purchase",
        trigger: "event",
        apps: ["DM_Store"],
      },
      {
        key: "SPNOTIFY",
        name: "Tim Hortons installation request",
        subject: "@Subject@",
        purpose: "Internal — TH installation request",
        trigger: "event",
        apps: ["DM_Store"],
      },
      {
        key: "PRTLTHWLCM",
        name: "Welcome to the Dynamic Media Portal!",
        subject: "Welcome to the Dynamic Media Portal!",
        purpose: "TH portal invitation (EN)",
        trigger: "event",
        apps: ["DM_Store", "CustomerCommunications"],
        step: 2,
      },
      {
        key: "PRTLTHWLCMFR",
        name: "Bienvenue sur le portail Dynamic Media!",
        subject: "Bienvenue sur le portail Dynamic Media!",
        purpose: "TH portal invitation (FR)",
        trigger: "event",
        apps: ["DM_Store", "CustomerCommunications"],
        step: 2,
      },
      {
        key: "THGETSTART",
        name: "[Important] Music Player Setup Guide – Save This Email",
        subject: "[Important] Music Player Setup Guide – Save This Email",
        purpose: "Setup guide (EN)",
        trigger: "event",
        apps: ["CRM", "CustomerCommunications"],
        step: 3,
      },
      {
        key: "THGETSTARTFR",
        name: "[Important] Guide de configuration du lecteur musical",
        subject:
          "[Important] Guide de configuration du lecteur musical – Conservez ce courriel",
        purpose: "Setup guide (FR)",
        trigger: "event",
        apps: ["CRM", "CustomerCommunications"],
        step: 3,
      },
      {
        key: "THREMOTECODE",
        name: "Music Control — No App Required",
        subject: "Music Control — No App Required",
        purpose: "Remote pairing codes",
        trigger: "event",
        apps: ["CustomerCommunications"],
      },
      {
        key: "THOrderShip",
        name: "Your Music Order Has Shipped!",
        subject: "Your Music Order Has Shipped!",
        purpose: "Order shipped",
        trigger: "event",
        apps: ["CRM"],
        step: 4,
      },
      {
        key: "THPLONLINE",
        name: "Your Music Players are Online!",
        subject: "Your Music Players are Online!",
        purpose: "Players online (EN)",
        trigger: "event",
        apps: ["CustomerCommunications"],
        step: 5,
      },
      {
        key: "THPLONLINEFR",
        name: "Vos lecteurs musicaux sont en ligne!",
        subject: "Vos lecteurs musicaux sont en ligne!",
        purpose: "Players online (FR)",
        trigger: "event",
        apps: ["CustomerCommunications"],
        step: 5,
      },
      {
        key: "THNOTONLINE",
        name: "Let's Get Your Music Players Online - Need Assistance?",
        subject: "Let's Get Your Music Players Online - Need Assistance?",
        purpose: "Offline help (EN)",
        trigger: "event",
        apps: ["CustomerCommunications"],
        step: 5,
      },
      {
        key: "THNOTONLINEFR",
        name: "Mettons vos lecteurs musicaux en ligne — Besoin d'aide?",
        subject: "Mettons vos lecteurs musicaux en ligne — Besoin d'aide?",
        purpose: "Offline help (FR)",
        trigger: "event",
        apps: ["CustomerCommunications"],
        step: 5,
      },
    ],
    openQuestions: [
      "Confirm production order: ship before vs after setup guide.",
      "Is THREMOTECODE always sent or on-demand?",
    ],
  },

  {
    id: "th-portal-access",
    sequenceKey: "Portal.TimHortons",
    name: "Portal Password Reset",
    businessProcess: "TH portal password reset",
    departmentSlug: "tim-hortons",
    processType: "trigger",
    summary:
      "On-demand Tim Hortons store portal password reset (EN / FR). Separate from fulfillment lifecycle.",
    sourceJobs: ["CRM", "DM_Store", "CustomerPortal"],
    enrollment: {
      summary: "TH portal user requests password reset.",
      details: ["Locale twin EN/FR."],
    },
    start: {
      summary: "Password reset requested.",
      triggers: ["Event: Tim Hortons portal password reset"],
    },
    stop: {
      summary: "After locale reset email sends.",
      details: ["STOP after PassResTH or PassResTHFR."],
    },
    suppression: {
      summary: "EN xor FR per request.",
      details: [],
    },
    entryStepId: "start",
    steps: [
      {
        id: "start",
        kind: "start",
        label: "Password reset requested",
        triggerKind: "event",
        triggerDetail: "TH store portal",
        next: "locale",
      },
      {
        id: "locale",
        kind: "branch",
        label: "Locale?",
        branches: [
          {
            id: "en",
            label: "English",
            condition: "EN",
            next: "reset-en",
            tone: "neutral",
          },
          {
            id: "fr",
            label: "French",
            condition: "FR",
            next: "reset-fr",
            tone: "neutral",
          },
        ],
      },
      {
        id: "reset-en",
        kind: "email",
        label: "Password reset (EN)",
        emailKey: "PassResTH",
        subject: "Tim Hortons Store - Password Reset",
        next: "exit",
      },
      {
        id: "reset-fr",
        kind: "email",
        label: "Password reset (FR)",
        emailKey: "PassResTHFR",
        subject: "Boutique Tim Hortons — Réinitialisation du mot de passe",
        next: "exit",
      },
      {
        id: "exit",
        kind: "exit",
        label: "Reset sent",
        exitTone: "success",
      },
    ],
    emails: [
      {
        key: "PassResTH",
        name: "Tim Hortons Store - Password Reset",
        subject: "Tim Hortons Store - Password Reset",
        purpose: "TH portal password reset (EN)",
        trigger: "event",
        apps: ["CRM", "DM_Store", "CustomerPortal"],
        step: 1,
      },
      {
        key: "PassResTHFR",
        name: "Boutique Tim Hortons — Réinitialisation du mot de passe",
        subject: "Boutique Tim Hortons — Réinitialisation du mot de passe",
        purpose: "TH portal password reset (FR)",
        trigger: "event",
        apps: ["CRM", "DM_Store", "CustomerPortal"],
        step: 1,
      },
    ],
  },
];
